### ISSUE TITLE
JoinConferenceButton

### ISSUE THREAD

**Issue by griffithcaleb** [DolbyIO/comms-uikit-react#17]
Hi there, 

I just have a clarifying question about the the `JoinConferenceButton`. 

The `onSuccess` callback prop of this component indicates that this action is creating a conference which I can confirm by the resulting API request made by clicking the button. 

Is there a solution in the UIkit to handle joining an already existing conference since the docs suggest creating via a backend API  call? 
```
The [Create](https://docs.dolby.io/communications-apis/reference/create-conference) REST API allows creating a conference from your backend. We recommend using this method as it allows you to control conferences from a single location. This way, you can update only your backend, instead of updating all applications using different platforms and SDKs. The Create REST API returns information about the created conference, such as the conference ID.
```

Thanks!

**Comment by Noviny** [comment]
Hi @griffithcaleb ,

We are currently relying on using the same `meetingName` as the source of truth - if you use the same `meetingName`, the create will join the existing created conference. As such, if you can share the existing name with your frontend app and provide it to the `joinConference` button this will work.

Hope that clarifies for you!
