### ISSUE TITLE
Avatar not showing in meeting while cam is off in meeting

### ISSUE THREAD

**Issue by minal-v** [DolbyIO/comms-uikit-react#36]
We have used [comms-uikit-react](https://github.com/DolbyIO/comms-uikit-react) for the live streaming solution. 

I have set the following participantInfo with the valid avatarUrl but it not showing in meeting vidio tiles. it showing first 2 char of the name 

Is there any configuration that i have missed

const participantInfo = {
    avatarUrl: `${profileImage}`,
    name:
      loggedInUser && (loggedInUser.firstName || loggedInUser.lastName)
        ? `${loggedInUser.firstName} ${loggedInUser.lastName}`
        : `Guest`,
    externalId: loggedInUser?.userId,
  };

**Comment by FabienLavocat** [comment]
The profile picture has not been implemented in this UIKit - https://github.com/DolbyIO/comms-uikit-react/blob/main/src/components/ui/Avatar/Avatar.tsx - you can update this file if you want to add support to it.
